name: Build & Push Staging Image

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push
        run: |
          docker build --build-arg VITE_API_BASE=${{ vars.VITE_API_BASE_STAGING }} -t ${{ secrets.REGISTRY_URL }}/zvuks-frontend:staging .
          docker push ${{ secrets.REGISTRY_URL }}/zvuks-frontend:staging
